### ISSUE TITLE
Failing Settings Check With Geyser/Floodgate

### ISSUE THREAD

**Issue by ZandercraftGames** [2LStudios-MC/AntiBot#10]
System that the plugin is on: Bungee

Explanation:
When connecting to the server on Bedrock edition through Floodgate/Geyser, it will kick the user for failing the settings check. Basically I am asking for Geyser/Floodgate support in the plugin 😄

**Comment by linsaftw** [comment]
Disable Settings check if having issues. No other way to fix other than that.
