### ISSUE TITLE
Soft Warn Error on PlayerHandshakeEvent

### ISSUE THREAD

**Issue by Stixil** [2LStudios-MC/AntiBot#25]
Just encountered this error, thank you for the help.
https://mcpaste.io/11be4dcf1861f392

**Comment by linsaftw** [comment]
![image](https://user-images.githubusercontent.com/25271111/95799255-80dfa680-0cca-11eb-8bfd-288040b1ff66.png)

Internal Java error. The only recommendation i can make is to make sure you have latest Java 8 version installed in your machine; Other versions might be unstable.

**Comment by Stixil** [comment]
Java 8, not 14? Java 8 is not even supported by Oracle anymore.
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by ytnoos** [comment]
The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time

**Comment by linsaftw** [comment]
> The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time

![image](https://user-images.githubusercontent.com/25271111/96171016-b2d74f80-0efa-11eb-8476-76f3d35a7326.png)

Clearly nothing to do with Threading but Java itself trying to cast a Node to a TreeNode. Something is wrong in the new Java implementation of HashMap.

> Java 8, not 14? Java 8 is not even supported by Oracle anymore.
> https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Well, their frequent updates broke a lot of stuff sadly. I had to switch to 8 because of almost nothing working properly anymore.

**Comment by ytnoos** [comment]
> > The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time
> 
> ![image](https://user-images.githubusercontent.com/25271111/96171016-b2d74f80-0efa-11eb-8476-76f3d35a7326.png)
> 
> Clearly nothing to do with Threading but Java itself trying to cast a Node to a TreeNode. Something is wrong in the new Java implementation of HashMap.
> 
> > Java 8, not 14? Java 8 is not even supported by Oracle anymore.
> > https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> 
> Well, their frequent updates broke a lot of stuff sadly. I had to switch to 8 because of almost nothing working properly anymore.

https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168

**Comment by linsaftw** [comment]
> > > The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25271111/96171016-b2d74f80-0efa-11eb-8476-76f3d35a7326.png)
> > Clearly nothing to do with Threading but Java itself trying to cast a Node to a TreeNode. Something is wrong in the new Java implementation of HashMap.
> > > Java 8, not 14? Java 8 is not even supported by Oracle anymore.
> > > https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> > 
> > 
> > Well, their frequent updates broke a lot of stuff sadly. I had to switch to 8 because of almost nothing working properly anymore.
> 
> https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168

Concurrency is not being used in this case.

**Comment by ytnoos** [comment]
> > > > The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/25271111/96171016-b2d74f80-0efa-11eb-8476-76f3d35a7326.png)
> > > Clearly nothing to do with Threading but Java itself trying to cast a Node to a TreeNode. Something is wrong in the new Java implementation of HashMap.
> > > > Java 8, not 14? Java 8 is not even supported by Oracle anymore.
> > > > https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> > > 
> > > 
> > > Well, their frequent updates broke a lot of stuff sadly. I had to switch to 8 because of almost nothing working properly anymore.
> > 
> > 
> > https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168
> 
> Concurrency is not being used in this case.

You are calling that method in different events, I'm pretty sure that is the problem

**Comment by linsaftw** [comment]
> > > > > The exception is probably thrown because that map is accessed by different threads at the same time, you should use a ConcurrentHashMap or make sure that the method will be accessed maximum of one thread at a time
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/25271111/96171016-b2d74f80-0efa-11eb-8476-76f3d35a7326.png)
> > > > Clearly nothing to do with Threading but Java itself trying to cast a Node to a TreeNode. Something is wrong in the new Java implementation of HashMap.
> > > > > Java 8, not 14? Java 8 is not even supported by Oracle anymore.
> > > > > https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> > > > 
> > > > 
> > > > Well, their frequent updates broke a lot of stuff sadly. I had to switch to 8 because of almost nothing working properly anymore.
> > > 
> > > 
> > > https://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode/29971168
> > 
> > 
> > Concurrency is not being used in this case.
> 
> You are calling that method in different events, I'm pretty sure that is the problem

I will try adding synchronized block. Anyways, i would need more info from the author. Like, it always happens or sometimes?
