### ISSUE TITLE
Prevent players from tabcomplete plugin command

### ISSUE THREAD

**Issue by eUipKh** [2LStudios-MC/AntiBot#26]
This change would prevent sending the tabcomplete-command to players without the `antibot.admin` permission:

[This](https://github.com/2LStudios-MC/AntiBot/blob/master/src/twolovers/antibot/bungee/commands/AntibotCommand.java#L27) line to this: `super("antibot", "antibot.admin", "ab");`

**Comment by linsaftw** [comment]
How do you allow non-admins to use antibot then? There are commands that you dont need `antibot.admin` to use but `antibot.notifications`.
