### ISSUE TITLE
whitelist and blacklist issues

### ISSUE THREAD

**Issue by ghost** [2LStudios-MC/AntiBot#27]
whitelist/blacklist saves to invalid empty path and /ab whitelist add <ip> doesn't save to file even after a restart

**Comment by linsaftw** [comment]
> whitelist/blacklist saves to invalid empty path and /ab whitelist add doesn't save to file even after a restart

That could be because Bungee doesn't have access to save the file. Please try in another machine and see if the same thing happens.
