### ISSUE TITLE
whitelist and blacklist issues

### ISSUE THREAD

**Issue by ghost** [2LStudios-MC/AntiBot#28]
**no, antibot is literally saving to a yml path of ""  (see https://github.com/2LStudios-MC/AntiBot/blob/5acce83b18591a8399bf3c8fc4e0bb003cea9579/src/twolovers/antibot/bungee/module/WhitelistModule.java#L67 )**

**Comment by linsaftw** [comment]
Which is the idea.

Maybe i will make it "whitelist" instead of "" soon so we don't make confusions here.

**Comment by ghost** [comment]
@LinsaFTW its bad practice to set to an empty path, since its not what yaml was designed to do, usually yaml throws an exception when setting to an empty path, not sure why bungee version doesn't.
