### ISSUE TITLE
Add an option to completly bypass checks for an IP adress.

### ISSUE THREAD

**Issue by d-513** [2LStudios-MC/AntiBot#3]
I am using https://github.com/GeyserMC/Geyser to allow crossplay on my server, but the antibot detects it and denies the connections. I tried manually adding the proxy IP to the whitelist.yml file, but didn't help. Would be nice if you added an option to do that.

**Comment by linsaftw** [comment]
Sadly whitelist already bypasses every check but ratelimit. Its the only solution.

You could specify more and i could help you. (What check is detecting Geyser)
