### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by falsomesias** [2LStudios-MC/AntiBot#8]
10.04 12:56:53 [Server] Server thread/ERROR Could not load 'plugins/AntiBot.jar' in folder 'plugins'
10.04 12:56:53 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
10.04 12:56:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
10.04 12:56:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
10.04 12:56:53 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
10.04 12:56:53 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
10.04 12:56:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
10.04 12:56:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
10.04 12:56:53 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
10.04 12:56:53 [Server] INFO ... 6 more

**Comment by linsaftw** [comment]
The plugin is for BungeeCord.
